name: cd

on:
  push:
    branches: [main]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: "1.23.0"

      - name: Install goose
        run: go install github.com/pressly/goose/v3/cmd/goose@latest

      - name: Build app
        run: ./scripts/buildprod.sh

      - id: 'auth'
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v2'

      - name: 'Use gcloud CLI'
        run: 'gcloud info'

      - name: Build docker image and push to Google Artifact Registry
        run: gcloud builds submit --tag us-east5-docker.pkg.dev/notely-466701/notely-ar-repo/notely:latest

      - name: Run database migrations
        run: ./scripts/migrateup.sh

      - name: Deploy to Google Cloud Run
        run: gcloud run deploy notely --image us-east5-docker.pkg.dev/notely-466701/notely-ar-repo/notely:latest --region us-east5 --allow-unauthenticated --project notely-466701 --max-instances=4

